config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :computers
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include HTTParty
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  def index
    page = params[:page] || 1
    @computers = HTTParty.get("https://sb-backendapi.azurewebsites.net/api/Computers?per_page=10&page=#{page}")
  end

  def show
    id = params[:id]
    @computer = HTTParty.get("https://sb-backendapi.azurewebsites.net/api/Computers/#{id}")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'json'

  before_action :fetch_data_from_api

  def index
    @total_computers = get_total_computers
    @total_users = get_total_users
  end

  private

  def fetch_data_from_api
    @computers = HTTParty.get('https://sb-backendapi.azurewebsites.net/api/Computers')
    @users = HTTParty.get('https://sb-backendapi.azurewebsites.net/api/Users')
  end

  def get_total_computers
    @computers.count
  end

  def get_total_users
    @users.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    page = params[:page] || 1
    @users = HTTParty.get("https://sb-backendapi.azurewebsites.net/api/Users?per_page=10&page=#{page}")
  end

  def show
    id = params[:id]
    @user = HTTParty.get("https://sb-backendapi.azurewebsites.net/api/Users/#{id}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/computers/index.html.erb
<table>
  <tr>
    <th>Display name</th>
    <th>OS</th>
    <th>OS version</th>
  </tr>
  <%= @computers.each do |computer| %>
    <tr>
      <td><%= computer.displayname %></td>
      <td><%= computer.os %></td>
      <td><%= computer.osVersion %></td>
    </tr>
  <% end %>
</table>

app/views/computers/show.html.erb
<div class="container">
  <div class="blue box single-item">
    <div class="header"><%= @computer["id"] %></div>
    <i class="fas fa-desktop"></i>
    <div class="data"><%= @computer["displayname"] %></div>
    <div><%= @computer["os"] %> &#149; <%= @computer["osVersion"] %></div>
    <div><%= @computer["domain"] %></div>
    <div><%= @computer["dnsHostName"] %> &#149; <%= @computer["ipAddress"] %></div>
    <div><%= @computer["managerId"] %></div>
  </div>

  <div class="footer"><%= link_to "Return to computer list", computers_path %>  &#149; <%= link_to "Home", root_path %></div>
</div>

app/views/home/index.html.erb
<div class="container">
  <%= link_to users_path do %>
    <div class="blue box group-info">
      <div class="header">Users</div>
      <i class="fas fa-user"></i>
      <div class="data"><%= @total_users %></div>
    </div>
  <% end %>

  <%= link_to computers_path do %>
    <div class="blue box group-info">
      <div class="header">Computers</div>
      <i class="fas fa-desktop"></i>
      <div class="data"><%= @total_computers %></div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STEALTHbits API exercise</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
  <table>
    <tr>
      <th class="left blue">Display name</th>
      <th class="left blue">OS</th>
      <th class="left blue">OS version</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td class="left"><%= link_to user["displayname"], user_path(user["id"]) %></td>
        <td class="left"><%= user["email"] %></td>
        <td class="left"><%= user["lastLogon"] %></td>
      </tr>
    <% end %>
  </table>

  <div class="footer"><%= link_to "Home", root_path %></div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="blue box single-item">
    <div class="header"><%= @user["id"] %></div>
    <i class="fas fa-user"></i>
    <div class="data"><%= @user["displayname"] %></div>
    <div class="bio-info">
      <%= @user["department"] %> &#149; <%= @user["title"] %><br />
      <%= @user["email"] %>
    </div>
    <div><%= @user["lastLogon"] %></div>
    <div><%= @user["homeDirectory"] %> &#149; <%= @user["domain"] %></div>
    <div><%= @user["managerId"] %></div>
  </div>

  <div class="footer"><%= link_to "Return to user list", users_path %> &#149; <%= link_to "Home", root_path %></div>
</div>